<a href="https://colab.research.google.com/github/maaz1234/Flask-Web-Framework/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/supermarkets.csv")

In [ ]:
df.head()

ID          Address           City  ... Country         Name Employees
0   1     3666 21st St  San Francisco  ...     USA      Madeira         8
1   2   735 Dolores St  San Francisco  ...     USA  Bready Shop        15
2   3      332 Hill St  San Francisco  ...     USA  Super River        25
3   4     3995 23rd St  San Francisco  ...     USA   Ben's Shop        10
4   5  1056 Sanchez St  San Francisco  ...     USA      Sanchez        12

[5 rows x 7 columns]

In [ ]:
df.drop("State", 1)

ID          Address           City Country         Name  Employees
0   1     3666 21st St  San Francisco     USA      Madeira          8
1   2   735 Dolores St  San Francisco     USA  Bready Shop         15
2   3      332 Hill St  San Francisco     USA  Super River         25
3   4     3995 23rd St  San Francisco     USA   Ben's Shop         10
4   5  1056 Sanchez St  San Francisco     USA      Sanchez         12
5   6  551 Alvarado St  San Francisco     USA   Richvalley         20

In [ ]:
df["name"] = ["maaz","omair","faizee","mphammad","javeed","yes"]

In [ ]:
df.head()

ID          Address           City  ...         Name Employees      name
0   1     3666 21st St  San Francisco  ...      Madeira         8      maaz
1   2   735 Dolores St  San Francisco  ...  Bready Shop        15     omair
2   3      332 Hill St  San Francisco  ...  Super River        25    faizee
3   4     3995 23rd St  San Francisco  ...   Ben's Shop        10  mphammad
4   5  1056 Sanchez St  San Francisco  ...      Sanchez        12    javeed

[5 rows x 8 columns]

In [ ]:
df.shape[1]

8

In [ ]:
df["Country"]=df["Country"]+"/"+"america"

In [ ]:
df

ID          Address           City  ...         Name Employees      name
0   1     3666 21st St  San Francisco  ...      Madeira         8      maaz
1   2   735 Dolores St  San Francisco  ...  Bready Shop        15     omair
2   3      332 Hill St  San Francisco  ...  Super River        25    faizee
3   4     3995 23rd St  San Francisco  ...   Ben's Shop        10  mphammad
4   5  1056 Sanchez St  San Francisco  ...      Sanchez        12    javeed
5   6  551 Alvarado St  San Francisco  ...   Richvalley        20       yes

[6 rows x 8 columns]

In [ ]:
df_t = df.T

In [ ]:
df_t

0               1  ...                4                5
ID                     1               2  ...                5                6
Address     3666 21st St  735 Dolores St  ...  1056 Sanchez St  551 Alvarado St
City       San Francisco   San Francisco  ...    San Francisco    San Francisco
State           CA 94114        CA 94119  ...       California         CA 94114
Country      USA/america     USA/america  ...      USA/america      USA/america
Name             Madeira     Bready Shop  ...          Sanchez       Richvalley
Employees              8              15  ...               12               20
name                maaz           omair  ...           javeed              yes

[8 rows x 6 columns]

In [ ]:
df

ID          Address           City  ...         Name Employees      name
0   1     3666 21st St  San Francisco  ...      Madeira         8      maaz
1   2   735 Dolores St  San Francisco  ...  Bready Shop        15     omair
2   3      332 Hill St  San Francisco  ...  Super River        25    faizee
3   4     3995 23rd St  San Francisco  ...   Ben's Shop        10  mphammad
4   5  1056 Sanchez St  San Francisco  ...      Sanchez        12    javeed
5   6  551 Alvarado St  San Francisco  ...   Richvalley        20       yes

[6 rows x 8 columns]

In [ ]:
pip install geopy

In [ ]:
import geopy
dir(geopy)

['ArcGIS',
 'AzureMaps',
 'Baidu',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'GeocodeFarm',
 'GoogleV3',
 'Here',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'TomTom',
 'What3Words',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'location',
 'point',
 'units',
 'util']

In [ ]:
# from geopy.geocoders import nominatim
!pip install Nominatim


  Created wheel for Nominatim: filename=nominatim-0.1-py3-none-any.whl size=2363 sha256=d6eddc0964cf404260690dbb3cdd1e13220f4d03a82f96899262edc0aae29d5a
  Stored in directory: /root/.cache/pip/wheels/37/00/9e/d904c390bfb174830ad3dcfd62af5544cee7d88bed4f8acedd
Successfully built Nominatim


In [ ]:
!pip install geocoders

ERROR: Could not find a version that satisfies the requirement geocoders (from versions: none)
ERROR: No matching distribution found for geocoders


In [ ]:
# from geopy.geocoders import nominatim
import nominatim as nom


In [ ]:
pip install geopy

In [ ]:
import geopy.geocoders 

In [ ]:
from geopy.geocoders import Nominatim

In [ ]:
nom=Nominatim()

/usr/local/lib/python3.7/dist-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning


In [ ]:
nom.geocode("735 Dolores St,india,CA 94119")

In [ ]:
n= nom.geocode("735 Dolores St,india,CA 94119")
print(n)

None


In [ ]:
m=nom.geocode("735 Dolores St,San Francisco,CA 94119")

In [ ]:
m.latitude

37.757826800000004

In [ ]:
type(m)

geopy.location.Location

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/supermarkets.csv")
df

ID          Address           City  ... Country         Name Employees
0   1     3666 21st St  San Francisco  ...     USA      Madeira         8
1   2   735 Dolores St  San Francisco  ...     USA  Bready Shop        15
2   3      332 Hill St  San Francisco  ...     USA  Super River        25
3   4     3995 23rd St  San Francisco  ...     USA   Ben's Shop        10
4   5  1056 Sanchez St  San Francisco  ...     USA      Sanchez        12
5   6  551 Alvarado St  San Francisco  ...     USA   Richvalley        20

[6 rows x 7 columns]

In [ ]:
df["Address"]=df["Address"]+","+df["City"]+","+df["State"]+","+df["Country"]
df

ID                                         Address  ...         Name Employees
0   1         3666 21st St,San Francisco,CA 94114,USA  ...      Madeira         8
1   2       735 Dolores St,San Francisco,CA 94119,USA  ...  Bready Shop        15
2   3  332 Hill St,San Francisco,California 94114,USA  ...  Super River        25
3   4         3995 23rd St,San Francisco,CA 94114,USA  ...   Ben's Shop        10
4   5    1056 Sanchez St,San Francisco,California,USA  ...      Sanchez        12
5   6      551 Alvarado St,San Francisco,CA 94114,USA  ...   Richvalley        20

[6 rows x 7 columns]

In [ ]:
df["coordinates"] = df["Address"].apply(nom.geocode)
df

ID  ...                                        coordinates
0   1  ...  (3666, 21st Street, Noe Valley, San Francisco,...
1   2  ...  (735, Dolores Street, Liberty Street Historic ...
2   3  ...  (332, Hill Street, Noe Valley, San Francisco, ...
3   4  ...  (3995, 23rd Street, Noe Valley, San Francisco,...
4   5  ...  (1056;1058;1060;1062, Sanchez Street, Noe Vall...
5   6  ...  (551, Alvarado Street, Noe Valley, San Francis...

[6 rows x 8 columns]

In [ ]:
df.coordinates[0]

Location(3666, 21st Street, Noe Valley, San Francisco, San Francisco City and County, San Francisco, California, 94114, United States, (37.75664965, -122.42940540299549, 0.0))

In [ ]:
df["latitude"] = df["coordinates"].apply(lambda x: x.latitude)

In [ ]:
df["latitude"] 

0    37.756650
1    37.757827
2    37.755836
3    37.752965
4    37.752144
5    37.753565
Name: latitude, dtype: float64

In [ ]:
df["longitude"] = df["coordinates"].apply(lambda x: x.longitude)

In [ ]:
df["longitude"]

0   -122.429405
1   -122.425392
2   -122.428832
3   -122.431714
4   -122.429977
5   -122.433249
Name: longitude, dtype: float64

In [ ]:
df

ID                                         Address  ...   latitude   longitude
0   1         3666 21st St,San Francisco,CA 94114,USA  ...  37.756650 -122.429405
1   2       735 Dolores St,San Francisco,CA 94119,USA  ...  37.757827 -122.425392
2   3  332 Hill St,San Francisco,California 94114,USA  ...  37.755836 -122.428832
3   4         3995 23rd St,San Francisco,CA 94114,USA  ...  37.752965 -122.431714
4   5    1056 Sanchez St,San Francisco,California,USA  ...  37.752144 -122.429977
5   6      551 Alvarado St,San Francisco,CA 94114,USA  ...  37.753565 -122.433249

[6 rows x 10 columns]

In [ ]:
dir(set)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [ ]:
myset = {25,52,"maaz",25,50}

In [ ]:
myset

{25, 50, 52, 'maaz'}

In [ ]:
print(type(myset))

<class 'set'>


In [ ]:
print(type([[25,25,2,8,9],[84,6,8,62,24],[]]))

<class 'list'>


In [ ]:
import numpy

In [ ]:
n = numpy.arange(24)

In [ ]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
type(n)

numpy.ndarray

In [ ]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
n.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
n.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
n = np.asarray([[25,25,2,8,9],[84,6,8,62,24],[]])

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [ ]:
type(n)

numpy.ndarray

In [ ]:
pip install opencv

ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
ERROR: No matching distribution found for opencv


In [ ]:
import cv2
cv2.__version__

'4.1.2'

In [ ]:
import cv2

In [ ]:
im= cv2.imread("/content/drive/MyDrive/smallgray.png",0)
print(im)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [ ]:
im[1:,2:4]

array([[255, 255],
       [255,  97]], dtype=uint8)

In [ ]:
for i in im.T:
  print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [ ]:
for i in im.flat:
  print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [ ]:
im

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
img = numpy.hstack((im,im,im))

In [ ]:
print(img)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [ ]:
img = numpy.vstack((im,im,im))

In [ ]:
print(img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [ ]:
lst= numpy.hsplit(img,5)

In [ ]:
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [ ]:
lst= numpy.vsplit(img,3)

In [ ]:
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [ ]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
im_g = cv2.imread("/content/drive/MyDrive/smallgray.png",1)
print(im_g)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [ ]:
cv2.imwrite("newsmall.png",im_g)

True

In [ ]:
a = [3,9,41,9,49]

In [ ]:
a[2:]

[41, 9, 49]