<a href="https://colab.research.google.com/github/maaz1234/Flask-Web-Framework/blob/main/wordembedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Vocabulary size
voc_size=10000

In [6]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4007, 9363, 2663, 720], [4007, 9363, 2663, 5867], [4007, 9467, 2663, 5962], [9804, 2794, 5919, 9440, 2849], [9804, 2794, 5919, 9440, 8258], [1895, 4007, 3644, 2663, 4944], [719, 2794, 4083, 9440]]


In [7]:
#Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4007 9363 2663  720]
 [   0    0    0    0 4007 9363 2663 5867]
 [   0    0    0    0 4007 9467 2663 5962]
 [   0    0    0 9804 2794 5919 9440 2849]
 [   0    0    0 9804 2794 5919 9440 8258]
 [   0    0    0 1895 4007 3644 2663 4944]
 [   0    0    0    0  719 2794 4083 9440]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569
   -0.00745566  0.01560907 -0.00613327  0.03882781 -0.03420001]
  [-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569
   -0.00745566  0.01560907 -0.00613327  0.03882781 -0.03420001]
  [-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569
   -0.00745566  0.01560907 -0.00613327  0.03882781 -0.03420001]
  [-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569
   -0.00745566  0.01560907 -0.00613327  0.03882781 -0.03420001]
  [ 0.02125565 -0.03128354  0.01922698  0.01550955  0.03432794
   -0.04914562 -0.01799097 -0.01565366 -0.0309807  -0.00090375]
  [ 0.02992154 -0.03884619 -0.03936899 -0.00423355 -0.04098105
   -0.03831118 -0.02938685 -0.04464925 -0.01289135 -0.03241193]
  [-0.02881387 -0.01348219  0.02373198 -0.00353427 -0.04719908
   -0.03703047 -0.02219162  0.02360935  0.00085817 -0.00968119]
  [ 0.00435277  0.03986833 -0.04278224  0.00453454 -0.00174081
    0.01916606 -0.04465353  0.03051733 -0.028325

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4007, 9363, 2663,  720], dtype=int32)

In [15]:

print(model.predict(embedded_docs)[0])

[[-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569 -0.00745566
   0.01560907 -0.00613327  0.03882781 -0.03420001]
 [-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569 -0.00745566
   0.01560907 -0.00613327  0.03882781 -0.03420001]
 [-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569 -0.00745566
   0.01560907 -0.00613327  0.03882781 -0.03420001]
 [-0.01707134 -0.03396242  0.00287837  0.03931333  0.01173569 -0.00745566
   0.01560907 -0.00613327  0.03882781 -0.03420001]
 [ 0.02125565 -0.03128354  0.01922698  0.01550955  0.03432794 -0.04914562
  -0.01799097 -0.01565366 -0.0309807  -0.00090375]
 [ 0.02992154 -0.03884619 -0.03936899 -0.00423355 -0.04098105 -0.03831118
  -0.02938685 -0.04464925 -0.01289135 -0.03241193]
 [-0.02881387 -0.01348219  0.02373198 -0.00353427 -0.04719908 -0.03703047
  -0.02219162  0.02360935  0.00085817 -0.00968119]
 [ 0.00435277  0.03986833 -0.04278224  0.00453454 -0.00174081  0.01916606
  -0.04465353  0.03051733 -0.02832508  0.04529879]]